### ISSUE TITLE
How do i create FirestoreServiceFlutter instance ?

### ISSUE THREAD

**Issue by manhpv-1697** [tekartik/firebase_firestore.dart#50]
i use this lib with null safety, but firebase_flutter folder was removed then i dont know how to create new instance of FirestoreServiceFlutter ?

**Comment by alextekartik** [comment]
The flutter part has moved here: https://github.com/tekartik/firebase_flutter/tree/master/firestore_flutter

**Comment by manhpv-1697** [comment]
@alextekartik thank u very much !
