### ISSUE TITLE
Support for FieldValue.arrayUnion() and FieldValue.arrayRemove()

### ISSUE THREAD

**Issue by sroddy** [tekartik/firebase_firestore.dart#9]
It would be really cool to have support for these two special values.
How hard do you think it would be to implement the feature?

Thanks a lot

**Comment by alextekartik** [comment]
I was not aware of them. Let me take a look at the various implementations (flutter, web, node) if any

**Comment by alextekartik** [comment]
I made an implementation for flutter and sembast. browser and node are not natively implemented yet (but it could be done easily)
